/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowCircleLeft: typeof import('./src/components/icons/ArrowCircleLeft.vue')['default']
    ArrowSend: typeof import('./src/components/icons/ArrowSend.vue')['default']
    Avatar: typeof import('./src/components/ui/Avatar.vue')['default']
    AvatarPreview: typeof import('./src/components/ui/AvatarPreview.vue')['default']
    CharacterModal: typeof import('./src/components/CharacterModal.vue')['default']
    CharacterSettingPanel: typeof import('./src/components/CharacterSettingPanel.vue')['default']
    CharactersPage: typeof import('./src/components/CharactersPage.vue')['default']
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/ui/ChatInput.vue')['default']
    ChatNew: typeof import('./src/components/icons/ChatNew.vue')['default']
    ChatPage: typeof import('./src/components/ChatPage.vue')['default']
    ChatPanel: typeof import('./src/components/ChatPanel.vue')['default']
    ChatSidebar: typeof import('./src/components/ChatSidebar.vue')['default']
    CreateSessionChatPanel: typeof import('./src/components/CreateSessionChatPanel.vue')['default']
    DefaultModelSettings: typeof import('./src/components/settings/DefaultModelSettings.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSliderOptional: typeof import('./src/components/ui/ElSliderOptional.vue')['default']
    FileItem: typeof import('./src/components/ui/FileItem.vue')['default']
    LeftBarIcon: typeof import('./src/components/icons/LeftBarIcon.vue')['default']
    Loading: typeof import('./src/components/icons/Loading.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MainSidebar: typeof import('./src/components/MainSidebar.vue')['default']
    MarkdownContent: typeof import('./src/components/MarkdownContent.vue')['default']
    MCPServers: typeof import('./src/components/settings/MCPServers.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageItemTurn: typeof import('./src/components/MessageItemTurn.vue')['default']
    ModelsProviderList: typeof import('./src/components/settings/ModelsProviderList.vue')['default']
    ModelsSettings: typeof import('./src/components/settings/ModelsSettings.vue')['default']
    Network: typeof import('./src/components/icons/Network.vue')['default']
    OpenAI: typeof import('./src/components/icons/OpenAI.vue')['default']
    PasswordPage: typeof import('./src/components/PasswordPage.vue')['default']
    RightBarIcon: typeof import('./src/components/icons/RightBarIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollContainer: typeof import('./src/components/ui/ScrollContainer.vue')['default']
    ScrollToBottomButton: typeof import('./src/components/ui/ScrollToBottomButton.vue')['default']
    SectionsAlt: typeof import('./src/components/icons/SectionsAlt.vue')['default']
    SessionSettingPanel: typeof import('./src/components/SessionSettingPanel.vue')['default']
    SettingsMainPage: typeof import('./src/components/settings/SettingsMainPage.vue')['default']
    SidebarLayout: typeof import('./src/components/ui/SidebarLayout.vue')['default']
    Stop: typeof import('./src/components/icons/Stop.vue')['default']
    Thinking: typeof import('./src/components/icons/Thinking.vue')['default']
    Thinking2: typeof import('./src/components/icons/Thinking2.vue')['default']
    TokenStatisticsModal: typeof import('./src/components/TokenStatisticsModal.vue')['default']
    Ui: typeof import('./src/components/test/ui.vue')['default']
    UiButton: typeof import('./src/components/ui/UiButton.vue')['default']
    UserProfile: typeof import('./src/components/settings/UserProfile.vue')['default']
    UserSecurity: typeof import('./src/components/settings/UserSecurity.vue')['default']
    UserSubaccounts: typeof import('./src/components/settings/UserSubaccounts.vue')['default']
  }
}
