ai_providers = {
    "aliyun": {
        "name": "阿里云",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1/",
        "api_key": "sk-b4ed412869c342b5b50a0f3177af5d5c",
        "enabled": True,
    },
    "LongCat": {
        "name": "美团",
        "base_url": "https://api.longcat.chat/openai/",
        "api_key": "ak_1SR0v347o67W8LP39k6mx1Xj0Xw6k",
        "enabled": True,
    },
    "siliconflow": {
        "name": "硅基流动",
        "base_url": "https://api.siliconflow.cn/v1/",
        "api_key": "sk-ccdjtlfjhfrkyhcsiijmwahhxaqnfplyaesoqigjvbizbmsy",
        "enabled": True,
    },
    "lmstudio": {
        "name": "LM Studio",
        "base_url": "http://192.168.3.25:1234/v1/",
        "api_key": "",
        "enabled": False,
    },
}


ai_models = [
    {
        "name": "deepseek-ai/DeepSeek-V3.2-Exp",
        "provider": "siliconflow",
        "model": "deepseek-ai/DeepSeek-V3.2-Exp",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "deepseek-ai/DeepSeek-R1",
        "provider": "siliconflow",
        "model": "deepseek-ai/DeepSeek-R1",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "Qwen/Qwen3-235B-A22B-Thinking-2507",
        "provider": "siliconflow",
        "model": "Qwen/Qwen3-235B-A22B-Thinking-2507",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen3-max-2025-09-23",
        "provider": "aliyun",
        "model": "qwen3-max-2025-09-23",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen3-next-80b-a3b-thinking",
        "provider": "aliyun",
        "model": "qwen3-next-80b-a3b-thinking",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
    {
        "name": "qwen3-next-80b-a3b-instruct",
        "provider": "aliyun",
        "model": "qwen3-next-80b-a3b-instruct",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "deepseek-v3.1",
        "provider": "aliyun",
        "model": "deepseek-v3.1",
        "type": "text-completion",
        "thinking": "optional",
        "enabled": True,
    },
    {
        "name": "deepseek-v3",
        "provider": "aliyun",
        "model": "deepseek-v3",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "deepseek-r1",
        "provider": "aliyun",
        "model": "deepseek-r1",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
    {
        "name": "deepseek-r1-0528",
        "provider": "aliyun",
        "model": "deepseek-r1-0528",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
    {
        "name": "deepseek-r1-distill-llama-70b",
        "provider": "aliyun",
        "model": "deepseek-r1-distill-llama-70b",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
    {
        "name": "deepseek-r1-distill-qwen-32b",
        "provider": "aliyun",
        "model": "deepseek-r1-distill-qwen-32b",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
    {
        "name": "deepseek-r1-distill-qwen-14b",
        "provider": "aliyun",
        "model": "deepseek-r1-distill-qwen-14b",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
    {
        "name": "deepseek-r1-distill-llama-8b",
        "provider": "aliyun",
        "model": "deepseek-r1-distill-llama-8b",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
    {
        "name": "deepseek-r1-distill-qwen-7b",
        "provider:": "aliyun",
        "model": "deepseek-r1-distill-qwen-7b",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
    {
        "name": "deepseek-r1-distill-qwen-1.5b",
        "provider": "aliyun",
        "model": "deepseek-r1-distill-qwen-1.5b",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
    {
        "name": "qwen1.5-7b-chat",
        "provider": "aliyun",
        "model": "qwen1.5-7b-chat",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen1.5-1.8b-chat",
        "provider": "aliyun",
        "model": "qwen1.5-1.8b-chat",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen1.5-72b-chat",
        "provider": "aliyun",
        "model": "qwen1.5-72b-chat",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen2.5-coder-3b-instruct",
        "provider": "aliyun",
        "model": "qwen2.5-coder-3b-instruct",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen2.5-coder-32b-instruct",
        "provider": "aliyun",
        "model": "qwen2.5-coder-32b-instruct",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen2.5-math-72b-instruct",
        "provider": "aliyun",
        "model": "qwen2.5-math-72b-instruct",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen3-0.6b",
        "provider": "aliyun",
        "model": "qwen3-0.6b",
        "type": "text-completion",
        "thinking": "optional",
        "enabled": True,
    },
    {
        "name": "qwen3-1.7b",
        "provider": "aliyun",
        "model": "qwen3-1.7b",
        "type": "text-completion",
        "thinking": "optional",
        "enabled": True,
    },
    {
        "name": "qwen3-4b",
        "provider": "aliyun",
        "model": "qwen3-4b",
        "type": "text-completion",
        "thinking": "optional",
        "enabled": True,
    },
    {
        "name": "qwen3-8b",
        "provider": "aliyun",
        "model": "qwen3-8b",
        "type": "text-completion",
        "thinking": "optional",
        "enabled": True,
    },
    {
        "name": "qwen3-14b",
        "provider": "aliyun",
        "model": "qwen3-14b",
        "type": "text-completion",
        "thinking": "optional",
        "enabled": True,
    },
    {
        "name": "qwen3-30b-a3b",
        "provider": "aliyun",
        "model": "qwen3-30b-a3b",
        "type": "text-completion",
        "thinking": "optional",
        "enabled": True,
    },
    {
        "name": "qwen3-32b",
        "provider": "aliyun",
        "model": "qwen3-32b",
        "type": "text-completion",
        "thinking": "optional",
        "enabled": True,
    },
    {
        "name": "qwen3-235b-a22b",
        "provider": "aliyun",
        "model": "qwen3-235b-a22b",
        "type": "text-completion",
        "thinking": "optional",
        "enabled": True,
    },
    {
        "name": "qwen3-1.8b-chat",
        "provider": "aliyun",
        "model": "qwen3-1.8b-chat",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen3-72b-chat",
        "provider": "aliyun",
        "model": "qwen3-72b-chat",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen-max",
        "provider": "aliyun",
        "model": "qwen-max",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen-max-preview",
        "provider": "aliyun",
        "model": "qwen-max-preview",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qvq-max-2025-05-15",
        "provider": "aliyun",
        "model": "qvq-max-2025-05-15",
        "type": "text-completion",
        "thinking": "unknown",
        "enabled": True,
    },
    {
        "name": "qwen2.5-72b-instruct",
        "provider": "aliyun",
        "model": "qwen2.5-72b-instruct",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen-plus",
        "provider": "aliyun",
        "model": "qwen-plus",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen-plus-2025-07-14",
        "provider": "aliyun",
        "model": "qwen-plus-2025-07-14",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen-plus-2025-09-11",
        "provider": "aliyun",
        "model": "qwen-plus-2025-09-11",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen-plus-latest",
        "provider": "aliyun",
        "model": "qwen-plus-latest",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "qwen-plus-character",
        "provider": "aliyun",
        "model": "qwen-plus-character",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    # 美团模式
    {
        "name": "LongCat-Flash-Chat",
        "provider": "LongCat",
        "model": "LongCat-Flash-Chat",
        "type": "text-completion",
        "thinking": "no",
        "enabled": True,
    },
    {
        "name": "LongCat-Flash-Thinking",
        "provider": "LongCat",
        "model": "LongCat-Flash-Thinking",
        "type": "text-completion",
        "thinking": "support",
        "enabled": True,
    },
]
