"""add turns_id

Revision ID: 0263d3f0e06c
Revises: 14c673112a55
Create Date: 2026-03-21 10:58:04.091195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0263d3f0e06c'
down_revision: Union[str, Sequence[str], None] = '14c673112a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('current_turns_id', sa.String(length=26), nullable=True))
    op.add_column('message_content', sa.Column('turns_id', sa.String(length=26), nullable=False))
    op.add_column('message_content', sa.Column('tool_calls', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_message_content_turns_id'), 'message_content', ['turns_id'], unique=False)
    op.drop_column('message_content', 'process_turns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_content', sa.Column('process_turns', sqlite.JSON(), nullable=True))
    op.drop_index(op.f('ix_message_content_turns_id'), table_name='message_content')
    op.drop_column('message_content', 'tool_calls')
    op.drop_column('message_content', 'turns_id')
    op.drop_column('message', 'current_turns_id')
    # ### end Alembic commands ###
