"""add model_provider.user_id field

Revision ID: 0d0bbd9878b3
Revises: 7fc508545c84
Create Date: 2025-12-03 21:13:24.047068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0bbd9878b3'
down_revision = '7fc508545c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=26), nullable=True))
        batch_op.create_index(batch_op.f('ix_model_provider_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_provider_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
