"""add process_turns

Revision ID: 14c673112a55
Revises: 50a6667e3683
Create Date: 2026-03-20 14:35:41.844871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c673112a55'
down_revision: Union[str, Sequence[str], None] = '50a6667e3683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_content', sa.Column('process_turns', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_content', 'process_turns')
    # ### end Alembic commands ###
