"""add tools column to mcp_server

Revision ID: 3daf0aa18f73
Revises: 175ed05a2735
Create Date: 2026-03-23 09:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3daf0aa18f73'
down_revision: Union[str, Sequence[str], None] = '175ed05a2735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server', sa.Column('tools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_server', 'tools')
    # ### end Alembic commands ###