"""add_foreign_keys

Revision ID: 3ddce34b41c6
Revises: 
Create Date: 2025-11-06 15:05:43.475628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddce34b41c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_file_message_id', 'message', ['message_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_message_session_id', 'session', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_summary_session_id', 'session', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_constraint('fk_summary_session_id', type_='foreignkey')

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_session_id', type_='foreignkey')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('fk_file_message_id', type_='foreignkey')

    # ### end Alembic commands ###
