"""add message_content

Revision ID: 5c49fa3fe8c8
Revises: d63342b5389a
Create Date: 2025-11-08 18:04:27.553108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import ulid

# revision identifiers, used by Alembic.
revision = '5c49fa3fe8c8'
down_revision = 'd63342b5389a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('reasoning_content', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='fk_message_content_message_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_content_message_id'), ['message_id'], unique=False)
        
    # 获取数据库连接
    conn = op.get_bind()
    
    # 查询现有 message 数据
    messages = conn.execute(sa.text("SELECT id, content, reasoning_content, created_at, updated_at, meta_data FROM message")).fetchall()
    
    # 逐条插入数据，为每条记录生成 ULID
    for msg in messages:
        new_id = str(ulid.new())
        conn.execute(
            sa.text("""
                INSERT INTO message_content (id, message_id, content, reasoning_content, is_current, created_at, updated_at, meta_data)
                VALUES (:id, :message_id, :content, :reasoning_content, TRUE, :created_at, :updated_at, :meta_data)
            """),
            {
                'id': new_id,
                'message_id': msg.id,
                'content': msg.content,
                'reasoning_content': msg.reasoning_content,
                'created_at': msg.created_at,
                'updated_at': msg.updated_at,
                'meta_data': msg.meta_data
            }
        )
        conn.commit()
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('token_count')
        batch_op.drop_column('meta_data')
        batch_op.drop_column('reasoning_content')

    # ### end Alembic commands ###
 

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ### 
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning_content', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('meta_data', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('token_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
    
    # 2. 从content表恢复数据
    # 修改后的数据恢复部分
    op.execute("""
        UPDATE message 
        SET content = (SELECT content FROM message_content WHERE message_id = message.id AND is_current = TRUE),
            reasoning_content = (SELECT reasoning_content FROM message_content WHERE message_id = message.id AND is_current = TRUE)
    """)
    
    with op.batch_alter_table('message_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_content_message_id'))

    op.drop_table('message_content')
    # ### end Alembic commands ###
