"""add model_id field

Revision ID: 6a1765216fb2
Revises: 5c49fa3fe8c8
Create Date: 2025-11-15 17:21:10.279988

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a1765216fb2"
down_revision = "5c49fa3fe8c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 第一步：只添加列
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model_id", sa.String(), nullable=True))

    # 第二步：在batch_alter_table上下文外进行数据迁移
    conn = op.get_bind()
    characters = conn.execute(
        sa.text("SELECT id, settings FROM character WHERE settings IS NOT NULL")
    )

    for char in characters:
        if char.settings:
            import json
            try:
                settings = json.loads(char.settings)
                model_id = settings.get("model_id")
                if model_id:
                    # 更新记录
                    conn.execute(
                        sa.text("UPDATE character SET model_id = :model_id WHERE id = :id"),
                        {"model_id": model_id, "id": char.id},
                    )
                    # 从settings中移除model_id
                    if "model_id" in settings:
                        del settings["model_id"]
                        # 更新settings字段
                        conn.execute(
                            sa.text("UPDATE character SET settings = :settings WHERE id = :id"),
                            {"settings": json.dumps(settings), "id": char.id},
                        )
            except json.JSONDecodeError:
                # 如果JSON解析失败，跳过该记录
                pass

    # 第三步：创建索引和外键
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_character_model_id"), ["model_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_character_model_id", "model", ["model_id"], ["id"], ondelete="SET NULL"
        )

    # 对session表也采用同样的模式
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model_id", sa.String(), nullable=True))

    # session表的数据迁移
    conn = op.get_bind()
    sessions = conn.execute(
        sa.text("SELECT id, settings FROM session WHERE settings IS NOT NULL")
    )

    for session in sessions:
        if session.settings:
            import json
            try:
                settings = json.loads(session.settings)
                model_id = settings.get("model_id")
                if model_id:
                    # 更新记录
                    conn.execute(
                        sa.text("UPDATE session SET model_id = :model_id WHERE id = :id"),
                        {"model_id": model_id, "id": session.id},
                    )
                    # 从settings中移除model_id
                    if "model_id" in settings:
                        del settings["model_id"]
                        # 更新settings字段
                        conn.execute(
                            sa.text("UPDATE session SET settings = :settings WHERE id = :id"),
                            {"settings": json.dumps(settings), "id": session.id},
                        )
            except json.JSONDecodeError:
                # 如果JSON解析失败，跳过该记录
                pass

    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_model_id"), ["model_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_session_model_id", "model", ["model_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###