"""add user.email and user.phone unique

Revision ID: 7ef1e5076c9e
Revises: 0d0bbd9878b3
Create Date: 2025-12-04 22:28:46.811241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef1e5076c9e'
down_revision = '0d0bbd9878b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    # ### end Alembic commands ###
