"""add user.parent_id,user.avater_url,character.is_public filedes

Revision ID: 7fc508545c84
Revises: fbb6352c5051
Create Date: 2025-12-03 15:31:45.822544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc508545c84'
down_revision = 'fbb6352c5051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.String(length=26), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_parent_id'))
        batch_op.drop_column('parent_id')
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
