"""fixed2

Revision ID: b857825bd0cb
Revises: 0263d3f0e06c
Create Date: 2026-03-21 13:21:40.298116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b857825bd0cb'
down_revision: Union[str, Sequence[str], None] = '0263d3f0e06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_content', sa.Column('additional_kwargs', sa.JSON(), nullable=True))
    op.drop_column('message_content', 'tool_calls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_content', sa.Column('tool_calls', sqlite.JSON(), nullable=True))
    op.drop_column('message_content', 'additional_kwargs')
    # ### end Alembic commands ###
