"""fixed2

Revision ID: b857825bd0cb
Revises: 0263d3f0e06c
Create Date: 2026-03-21 13:21:40.298116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b857825bd0cb'
down_revision: Union[str, Sequence[str], None] = '0263d3f0e06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_message_old_20260321')
    op.add_column('message_content', sa.Column('additional_kwargs', sa.JSON(), nullable=True))
    op.drop_column('message_content', 'tool_calls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_content', sa.Column('tool_calls', sqlite.JSON(), nullable=True))
    op.drop_column('message_content', 'additional_kwargs')
    op.create_table('_message_old_20260321',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('current_turns_id', sa.VARCHAR(length=26), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_message_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
