"""add_foreign_keys

Revision ID: d53d4cb3cbe6
Revises: 3ddce34b41c6
Create Date: 2025-11-06 15:19:41.179606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53d4cb3cbe6'
down_revision = '3ddce34b41c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_model_provider_id'), ['provider_id'], unique=False)
        batch_op.create_foreign_key('fk_model_provider_id', 'model_provider', ['provider_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_constraint('fk_model_provider_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_model_provider_id'))
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
