"""fixed field name

Revision ID: d63342b5389a
Revises: d53d4cb3cbe6
Create Date: 2025-11-06 17:23:41.966457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63342b5389a'
down_revision = 'd53d4cb3cbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_extension', sa.String(length=100), nullable=False))
        batch_op.drop_column('file_extiension')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_extiension', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('file_extension')

    # ### end Alembic commands ###
