"""fixed3

Revision ID: d8dc8ea173ed
Revises: b857825bd0cb
Create Date: 2026-03-21 13:27:19.524237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8dc8ea173ed'
down_revision: Union[str, Sequence[str], None] = 'b857825bd0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_content', sa.Column('role', sa.String(length=32), nullable=True))
    op.drop_column('message_content', 'is_current')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_content', sa.Column('is_current', sa.BOOLEAN(), nullable=True))
    op.drop_column('message_content', 'role')
    # ### end Alembic commands ###
