"""modfiy file and message model

Revision ID: fbb6352c5051
Revises: 6a1765216fb2
Create Date: 2025-11-28 17:13:08.781611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb6352c5051'
down_revision = '6a1765216fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_file_message_id', 'message', ['message_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('fk_file_message_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'message', ['message_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
